# Generated by Django 4.1.3 on 2022-12-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_livros_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='data_emprestimo',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='tempo_duracao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
    ]
